// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDavR64VJfhIlbD4pes3-0YHe8zhon1CcI',
    appId: '1:761801883752:web:6c5cdb3cdcfc3b3ea7fbdd',
    messagingSenderId: '761801883752',
    projectId: 'localisation-9cfda',
    authDomain: 'localisation-9cfda.firebaseapp.com',
    databaseURL: 'https://localisation-9cfda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'localisation-9cfda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnrgxuTNdlJGSRr9UhLrQeqLuwDJGRmlY',
    appId: '1:761801883752:android:1a9cec6a0b43a95da7fbdd',
    messagingSenderId: '761801883752',
    projectId: 'localisation-9cfda',
    databaseURL: 'https://localisation-9cfda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'localisation-9cfda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-vPNwM46BSEDY1yy3NgQ2IDphZIiDTDo',
    appId: '1:761801883752:ios:94ec40e44d61db5ca7fbdd',
    messagingSenderId: '761801883752',
    projectId: 'localisation-9cfda',
    databaseURL: 'https://localisation-9cfda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'localisation-9cfda.appspot.com',
    iosClientId: '761801883752-uc760aj5v0gt23mst94mo6vri5efs4kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.applilocali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-vPNwM46BSEDY1yy3NgQ2IDphZIiDTDo',
    appId: '1:761801883752:ios:94ec40e44d61db5ca7fbdd',
    messagingSenderId: '761801883752',
    projectId: 'localisation-9cfda',
    databaseURL: 'https://localisation-9cfda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'localisation-9cfda.appspot.com',
    iosClientId: '761801883752-uc760aj5v0gt23mst94mo6vri5efs4kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.applilocali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDavR64VJfhIlbD4pes3-0YHe8zhon1CcI',
    appId: '1:761801883752:web:810e31c18d4700a5a7fbdd',
    messagingSenderId: '761801883752',
    projectId: 'localisation-9cfda',
    authDomain: 'localisation-9cfda.firebaseapp.com',
    databaseURL: 'https://localisation-9cfda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'localisation-9cfda.appspot.com',
  );

}